name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    - name: Lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        config: golangci.yml
    - name: Tidy mod
      run: go mod tidy
    - name: Build
      run: go build -v -o build_test .
    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic -v ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3